# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Nick DelRossi
tagline:             ''
description:         'Software Engineer localed in Boston'
url:                 https://www.nickdelrossi.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Nick DelRossi
  url:               https:www.nickdelrossi/com
  email:             nick@nickdelrossi.com

# Custom vars
version:             1.0.0

gems:                [jekyll-paginate]
