# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Nick DelRossi
tagline:             ''
description:         "Hi. I'm Nick DelRossi, Software Engineer at Acquia in Boston. My main areas of focus are around software quality, testing and continuous integration"
url:                 https://www.nickdelrossi.com
baseurl:
paginate:            5
comments:            true
disqus_short_name:   nickdelrossi

# About/contact
author:
  name:              Nick DelRossi
  url:               https://www.nickdelrossi.com
  email:             nick@nickdelrossi.com

# Custom vars
version:             1.0.0

gems:                [jekyll-paginate]

# Links
links:
  github:            https://github.com/ndelrossi
